name: Terraform Deploy

on:
 # workflow_dispatch:
 push:
  branches:
  - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.3

    # Set up AWS credentials from GitHub Secrets
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
    # install terraform docs
    - name: terraform docs
      run: sudo snap install terraform-docs

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Generate Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Generate markdown file for PR review
    - name: Generate README.md with terraform-docs
      run: terraform-docs markdown . > README.md

    # Upload the generated markdown as an artifact for PR review
    - name: Upload Terraform Plan Markdown
      uses: actions/upload-artifact@v4.6.0
      with:
        name: terraform-plan
        path: README.md

    # Apply Terraform Plan to create resources on AWS
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
