name: Terraform AWS Ec2 Deploy

on:
 # push:
 # branches:
   # - main  # Trigger on push to the main branch
 pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.3

    # Set up AWS credentials from GitHub Secrets
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
  
    # install terraform docs
    - name: terraform docs
      run: sudo snap install terraform-docs

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Generate Terraform Plan in the PR (pull_request event)
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'  # Only run for PR events
      run: terraform plan -out=tfplan

    # Generate Markdown documentation from Terraform plan for PR review
    - name: Generate Terraform Documentation
      if: github.event_name == 'pull_request'  # Only run for PR events
      run: terraform-docs markdown . > terraform-docs.md

    # Upload Terraform Docs for PR review
    - name: Upload Terraform Docs for PR review
      if: github.event_name == 'pull_request'  # Only run for PR events
      uses: actions/upload-artifact@v4.6.0
      with:
       name: terraform-docs
       path: terraform-docs.md

    # Apply Terraform Plan when the PR is merged (push to main branch)
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only run after PR is merged into main
      run: terraform apply -auto-approve tfplan
